version: '3'

services:
  app:
    build: .
    image: php:8-laravel
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  db:
    driver: local
